# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bclscrefFByLUAoqAe1WC6mWVe8gnc4H
"""

print("テストが表示できるか試しましょう")

